import{a as g,S as b,i}from"./assets/vendor-BWiIACaD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))p(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&p(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function p(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const w="48944298-6db138da2f96cff679e6bbba9",E="https://pixabay.com/api/",u=40;function f(s,r){return g.get(E,{params:{key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:u,page:r}}).then(e=>e.data).catch(e=>{throw console.error("Error fetching images:",e.message),new Error(e.message)})}const m=document.querySelector(".gallery");if(!m)throw new Error("Gallery element not found!");const L=new b(".gallery a");function h(s){const r=s.map(e=>`
        <a href="${e.largeImageURL}" class="gallery-item" title="${e.tags}">
            <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
            <div class="info">
                <span>Likes: ${e.likes}</span>
                <span>Views: ${e.views}</span>
                <span>Comments: ${e.comments}</span>
                <span>Downloads: ${e.downloads}</span>
            </div>
        </a>
    `).join("");m.insertAdjacentHTML("beforeend",r),L.refresh()}function S(){m.innerHTML=""}const q=document.querySelector("#search-form"),v=document.querySelector(".gallery"),a=document.querySelector(".loader"),n=document.querySelector(".load-more");let c="",l=1,y=0;q.addEventListener("submit",s=>{if(s.preventDefault(),c=s.target.elements.searchQuery.value.trim(),!c){i.warning({title:"Warning",message:"Please enter a search query"});return}l=1,S(),n.style.display="none",a.style.display="block",f(c,l).then(r=>{y=r.totalHits,r.hits.length===0?(n.style.display="none",i.error({title:"Error",message:"No images found, try another query"})):(h(r.hits),y>u&&(n.style.display="block"))}).catch(()=>i.error({title:"Error",message:"Something went wrong"})).finally(()=>a.style.display="none")});n.addEventListener("click",()=>{l+=1,n.style.display="none",a.style.display="block",f(c,l).then(s=>{h(s.hits),l*u>=y?(n.style.display="none",i.info({message:"We're sorry, but you've reached the end of search results."})):n.style.display="block";const{height:r}=v.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}).catch(()=>i.error({title:"Error",message:"Something went wrong"})).finally(()=>a.style.display="none")});a.style.display="block";setTimeout(()=>{f(c,l).then(s=>{}).finally(()=>a.style.display="none")},2e3);
//# sourceMappingURL=index.js.map
