import{a as g,S as w,i as a}from"./assets/vendor-tnUJPedx.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))p(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&p(u)}).observe(document,{childList:!0,subtree:!0});function t(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function p(r){if(r.ep)return;r.ep=!0;const o=t(r);fetch(r.href,o)}})();const b="48944298-6db138da2f96cff679e6bbba9",L="https://pixabay.com/api/",y=40;async function m(s,e){try{return(await g.get(L,{params:{key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:y,page:e}})).data}catch(t){throw new Error(t.message)}}const f=document.querySelector(".gallery");if(!f)throw new Error("Gallery element not found!");const E=new w(".gallery a");function h(s){const e=s.map(t=>`
        <a href="${t.largeImageURL}" class="gallery-item" title="${t.tags}">
            <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
            <div class="info">
                <span>Likes: ${t.likes}</span>
                <span>Views: ${t.views}</span>
                <span>Comments: ${t.comments}</span>
                <span>Downloads: ${t.downloads}</span>
            </div>
        </a>
    `).join("");f.insertAdjacentHTML("beforeend",e),E.refresh()}function S(){f.innerHTML=""}const q=document.querySelector("#search-form"),v=document.querySelector(".gallery"),c=document.querySelector(".loader"),n=document.querySelector(".load-more");let l="",i=1,d=0;async function $(s){if(s.preventDefault(),l=s.target.elements.searchQuery.value.trim(),!l){a.warning({title:"Warning",message:"Please enter a search query"});return}i=1,S(),n.style.display="none",c.style.display="block";try{const e=await m(l,i);d=e.totalHits,e.hits.length===0?a.error({title:"Error",message:"No images found, try another query"}):(h(e.hits),d>y&&(n.style.display="block"))}catch{a.error({title:"Error",message:"Something went wrong"})}finally{c.style.display="none"}}async function P(){var s;if(l){i+=1,n.style.display="none",c.style.display="block";try{const e=await m(l,i);h(e.hits),i*y>=d?(n.style.display="none",a.info({message:"We're sorry, but you've reached the end of search results."})):n.style.display="block";const{height:t}=((s=v.firstElementChild)==null?void 0:s.getBoundingClientRect())||{height:0};window.scrollBy({top:t*2,behavior:"smooth"})}catch{a.error({title:"Error",message:"Something went wrong"})}finally{c.style.display="none"}}}q.addEventListener("submit",$);n.addEventListener("click",P);d>y&&(n.style.display="block");
//# sourceMappingURL=index.js.map
